server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
auth:
  jwt:
    pubKeyPath: D:\project-0713\rsa\rsa.pub
    priKeyPath: D:\project-0713\rsa\rsa.pri
    secret: 1239DJOERI239#$*423sdsRER
    expire: 180
    cookieName: GMALL-TOKEN
    unick: unick
